#!/bin/bash

AUTH_TOKEN=$(security find-generic-password -w -a alan -s alan--meilisearch--scratchpad--search-key)


if [ "$1" ]
   then 
       curl -s \
            -X POST 'http://127.0.0.1:7700/indexes/grimoire/search' \
            -H "Authorization: Bearer $AUTH_TOKEN" \
            -H 'Content-Type: application/json' \
            --data-binary "{ \"q\": \"$1\" }" \
                  | \
                  /opt/homebrew/bin/jq \
                                  -r \
                                  '.hits[] | .filename'
else
echo "Ready..."

fi 
